DAAP_SERVER = 'Euphony/0.1'

MDNS_TYPE_SERVER = '_touch-able._tcp.local.'
MDNS_TYPE_REMOTE = '_touch-remote._tcp.local.'

DACP_TIMEOUT = 1800

DMAP_PROTOCOL_VERSION = (2, 0, 6, 0)
DAAP_PROTOCOL_VERSION = (3, 0, 8, 0)
ITUNES_SHARING_VERSION = (3, 0, 1, 0)

PLAYER_STATE_STOPPED = 2
PLAYER_STATE_PAUSED = 3
PLAYER_STATE_PLAYING = 4
SHUFFLE_STATE_OFF = 0
SHUFFLE_STATE_ON = 1
REPEAT_STATE_OFF = 0
REPEAT_STATE_SINGLE = 1
REPEAT_STATE_ON = 2

AVAILABLE_REPEAT_STATES = 2
AVAILABLE_SHUFFLE_STATES = 2

VOLUME_CONTROLLABLE = 1

PARAMETER_REGEX = r"([^,+']+?)[:!]([^,+']+)"

BASE_PLAYLIST = 'Library'
