# The MIT License
#
# Copyright (c) 2010 Ryan Bergstrom
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

_TAG_DATA = (
    ('abal', 'daap.browsealbumlisting', 'ContainerValue'),
    ('abar', 'daap.browseartistlisting', 'ContainerValue'),
    ('abcp', 'daap.browsecomposerlisting', 'ContainerValue'),
    ('abgn', 'daap.browsegenrelisting', 'ContainerValue'),
    ('abpl', 'daap.baseplaylist', 'UByteValue'),
    ('abro', 'daap.databasebrowse', 'ContainerValue'),
    ('adbs', 'daap.databasesongs', 'ContainerValue'),
    ('aeAD', 'com.apple.itunes.adam-ids-array', 'ContainerValue'),
    ('aeAI', 'com.apple.itunes.itms-artistid', 'UIntValue'),
    ('aeCI', 'com.apple.itunes.itms-composerid', 'UIntValue'),
    ('aeCR', 'com.apple.itunes.content-rating', 'StringValue'),
    ('aeDP', 'com.apple.itunes.drm-platform-id', 'UIntValue'),
    ('aeDR', 'com.apple.itunes.drm-user-id', 'ULongValue'),
    ('aeDV', 'com.apple.itunes.drm-versions', 'UIntValue'),
    ('aeEN', 'com.apple.itunes.episode-num-str', 'StringValue'),
    ('aeES', 'com.apple.itunes.episode-sort', 'UIntValue'),
    ('aeFP', 'com.apple.itunes.req-fplay', 'UByteValue'),
    ('aeGD', 'com.apple.itunes.gapless-enc-dr', 'UIntValue'),
    ('aeGE', 'com.apple.itunes.gapless-enc-del', 'UIntValue'),
    ('aeGH', 'com.apple.itunes.gapless-heur', 'UIntValue'),
    ('aeGI', 'com.apple.itunes.itms-genreid', 'UIntValue'),
    ('aeGR', 'com.apple.itunes.gapless-resy', 'ULongValue'),
    ('aeGU', 'com.apple.itunes.gapless-dur', 'ULongValue'),
    ('aeHD', 'com.apple.itunes.is-hd-video', 'UByteValue'),
    ('aeHV', 'com.apple.itunes.has-video', 'UByteValue'),
    ('aeK1', 'com.apple.itunes.drm-key1-id', 'ULongValue'),
    ('aeK2', 'com.apple.itunes.drm-key2-id', 'ULongValue'),
    ('aeMk', 'com.apple.itunes.extended-media-kind', 'UIntValue'),
    ('aeMK', 'com.apple.itunes.mediakind', 'UByteValue'),
    ('aeND', 'com.apple.itunes.non-drm-user-id', 'ULongValue'),
    ('aeNN', 'com.apple.itunes.network-name', 'StringValue'),
    ('aeNV', 'com.apple.itunes.norm-volume', 'UIntValue'),
    ('aePC', 'com.apple.itunes.is-podcast', 'UByteValue'),
    ('aePI', 'com.apple.itunes.itms-playlistid', 'UIntValue'),
    ('aePP', 'com.apple.itunes.is-podcast-playlist', 'UByteValue'),
    ('aePS', 'com.apple.itunes.special-playlist', 'UByteValue'),
    ('aeSE', 'com.apple.itunes.store-pers-id', 'ULongValue'),
    ('aeSF', 'com.apple.itunes.itms-storefrontid', 'UIntValue'),
    ('aeSG', 'com.apple.itunes.saved-genius', 'UByteValue'),
    ('aeSI', 'com.apple.itunes.itms-songid', 'UIntValue'),
    ('aeSN', 'com.apple.itunes.series-name', 'StringValue'),
    ('aeSP', 'com.apple.itunes.smart-playlist', 'UByteValue'),
    ('aeSU', 'com.apple.itunes.season-num', 'UIntValue'),
    ('aeSV', 'com.apple.itunes.music-sharing-version', 'VersionValue'),
    ('aeXD', 'com.apple.itunes.xid', 'StringValue'),
    ('agal', None, 'ContainerValue'),
    ('agrp', 'daap.songgrouping', 'StringValue'),
    ('aply', 'daap.databaseplaylists', 'ContainerValue'),
    ('aprm', 'daap.playlistrepeatmode', 'UByteValue'),
    ('apro', 'daap.protocolversion', 'VersionValue'),
    ('apsm', 'daap.playlistshufflemode', 'UByteValue'),
    ('apso', 'daap.playlistsongs', 'ContainerValue'),
    ('arif', 'daap.resolveinfo', 'ContainerValue'),
    ('arsv', 'daap.resolve', 'ContainerValue'),
    ('asaa', 'daap.songalbumartist', 'StringValue'),
    ('asai', 'daap.songalbumid', 'ULongValue'),
    ('asal', 'daap.songalbum', 'StringValue'),
    ('asar', 'daap.songartist', 'StringValue'),
    ('asbk', 'daap.bookmarkable', 'UByteValue'),
    ('asbo', 'daap.songbookmark', 'UIntValue'),
    ('asbr', 'daap.songbitrate', 'UShortValue'),
    ('asbt', 'daap.songbeatsperminute', 'UShortValue'),
    ('ascd', 'daap.songcodectype', 'UIntValue'),
    ('ascm', 'daap.songcomment', 'StringValue'),
    ('ascn', 'daap.songcontentdescription', 'StringValue'),
    ('asco', 'daap.songcompilation', 'UByteValue'),
    ('ascp', 'daap.songcomposer', 'StringValue'),
    ('ascr', 'daap.songcontentrating', 'UByteValue'),
    ('ascs', 'daap.songcodecsubtype', 'UIntValue'),
    ('asct', 'daap.songcategory', 'StringValue'),
    ('asda', 'daap.songdateadded', 'DatetimeValue'),
    ('asdb', 'daap.songdisabled', 'UByteValue'),
    ('asdc', 'daap.songdisccount', 'UShortValue'),
    ('asdk', 'daap.songdatakind', 'UByteValue'),
    ('asdm', 'daap.songdatemodified', 'DatetimeValue'),
    ('asdn', 'daap.songdiscnumber', 'UShortValue'),
    ('asdp', 'daap.songdatepurchased', 'DatetimeValue'),
    ('asdr', 'daap.songdatereleased', 'DatetimeValue'),
    ('asdt', 'daap.songdescription', 'StringValue'),
    ('ased', 'daap.songextradata', 'UShortValue'),
    ('aseq', 'daap.songeqpreset', 'StringValue'),
    ('asfm', 'daap.songformat', 'StringValue'),
    ('asgn', 'daap.songgenre', 'StringValue'),
    ('asgp', 'daap.songgapless', 'UByteValue'),
    ('ashp', 'daap.songhasbeenplayed', 'UByteValue'),
    ('asky', 'daap.songkeywords', 'StringValue'),
    ('aslc', 'daap.songlongcontentdescription', 'StringValue'),
    ('asls', 'daap.songlongsize', 'ULongValue'),
    ('aspu', 'daap.songpodcasturl', 'StringValue'),
    ('asrv', 'daap.songrelativevolume', 'ByteValue'),
    ('assa', 'daap.sortartist', 'StringValue'),
    ('assc', 'daap.sortcomposer', 'StringValue'),
    ('assl', 'daap.sortalbumartist', 'StringValue'),
    ('assn', 'daap.sortname', 'StringValue'),
    ('assp', 'daap.songstoptime', 'UIntValue'),
    ('assr', 'daap.songsamplerate', 'UIntValue'),
    ('asss', 'daap.sortseriesname', 'StringValue'),
    ('asst', 'daap.songstarttime', 'UIntValue'),
    ('assu', 'daap.sortalbum', 'StringValue'),
    ('assz', 'daap.songsize', 'UIntValue'),
    ('astc', 'daap.songtrackcount', 'UShortValue'),
    ('astm', 'daap.songtime', 'UIntValue'),
    ('astn', 'daap.songtracknumber', 'UShortValue'),
    ('asul', 'daap.songdataurl', 'StringValue'),
    ('asur', 'daap.songuserrating', 'UByteValue'),
    ('asyr', 'daap.songyear', 'UShortValue'),
    ('ated', 'daap.supportsextradata', 'UShortValue'),
    ('avdb', 'daap.serverdatabases', 'ContainerValue'),
    ('caar', 'dacp.availablerepeatstates', 'UIntValue'),
    ('caas', 'dacp.availableshufflestates', 'UIntValue'),
    ('caci', None, 'ContainerValue'),
    ('cacr', None, 'ContainerValue'),
    ('caia', None, 'UByteValue'),
    ('cana', None, 'StringValue'),
    ('cang', None, 'StringValue'),
    ('canl', None, 'StringValue'),
    ('cann', None, 'StringValue'),
    ('canp', 'dacp.nowplaying', 'MultiUIntValue'),
    ('cant', None, 'UIntValue'),
    ('caps', 'dacp.playerstate', 'UByteValue'),
    ('carp', 'dacp.repeatstate', 'UByteValue'),
    ('cash', 'dacp.shufflestate', 'UByteValue'),
    ('casp', None, 'ContainerValue'),
    ('cass', None, 'UByteValue'),
    ('cast', None, 'UIntValue'),
    ('casu', None, 'UByteValue'),
    ('cavc', 'dacp.volumecontrollable', 'UByteValue'),
    ('ceGS', None, 'UByteValue'),
    ('ceJC', 'com.apple.itunes.jukebox-client-vote', 'ByteValue'),
    ('ceJI', 'com.apple.itunes.jukebox-current', 'UIntValue'),
    ('ceJS', 'com.apple.itunes.jukebox-score', 'ShortValue'),
    ('ceJV', 'com.apple.itunes.jukebox-vote', 'UIntValue'),
    ('ceSG', None, 'UByteValue'),
    ('ceVO', None, 'UByteValue'),
    ('ceWM', None, 'BinaryValue'),
    ('cmgt', None, 'ContainerValue'),
    ('cmik', None, 'UByteValue'),
    ('cmmk', None, 'UIntValue'),
    ('cmnm', None, 'StringValue'),
    ('cmpa', None, 'ContainerValue'),
    ('cmpg', None, 'ULongValue'),
    ('cmsp', None, 'UByteValue'),
    ('cmsr', None, 'UIntValue'),
    ('cmst', None, 'ContainerValue'),
    ('cmsv', None, 'UByteValue'),
    ('cmty', None, 'StringValue'),
    ('cmvo', 'dmcp.volume', 'UIntValue'),
    ('mbcl', 'dmap.bag', 'ContainerValue'),
    ('mccr', 'dmap.contentcodesresponse', 'ContainerValue'),
    ('mcna', 'dmap.contentcodesname', 'StringValue'),
    ('mcnm', 'dmap.contentcodesnumber', 'UIntValue'),
    ('mcon', 'dmap.container', 'ContainerValue'),
    ('mctc', 'dmap.containercount', 'UIntValue'),
    ('mcti', 'dmap.containeritemid', 'UIntValue'),
    ('mcty', 'dmap.contentcodestype', 'UShortValue'),
    ('mdcl', 'dmap.dictionary', 'ContainerValue'),
    ('medc', None, 'ContainerValue'),
    ('meds', 'dmap.editcommandssupported', 'UIntValue'),
    ('miid', 'dmap.itemid', 'UIntValue'),
    ('mikd', 'dmap.itemkind', 'UByteValue'),
    ('mimc', 'dmap.itemcount', 'UIntValue'),
    ('minm', 'dmap.itemname', 'StringValue'),
    ('mlcl', 'dmap.listing', 'ContainerValue'),
    ('mlid', 'dmap.sessionid', 'UIntValue'),
    ('mlit', 'dmap.listingitem', 'ContainerValue'),
    ('mlog', 'dmap.loginresponse', 'ContainerValue'),
    ('mpco', 'dmap.parentcontainerid', 'UIntValue'),
    ('mper', 'dmap.persistentid', 'ULongValue'),
    ('mpro', 'dmap.protocolversion', 'VersionValue'),
    ('mrco', 'dmap.returnedcount', 'UIntValue'),
    ('msal', 'dmap.supportsautologout', 'UByteValue'),
    ('msas', 'dmap.authenticationschemes', 'UByteValue'),
    ('msau', 'dmap.authenticationmethod', 'UByteValue'),
    ('msbr', 'dmap.supportsbrowse', 'UByteValue'),
    ('msdc', 'dmap.databasescount', 'UIntValue'),
    ('msed', None, 'UByteValue'),
    ('msex', 'dmap.supportsextensions', 'UByteValue'),
    ('mshc', None, 'UShortValue'),
    ('mshi', None, 'UIntValue'),
    ('mshl', None, 'ContainerValue'),
    ('mshn', None, 'UIntValue'),
    ('msix', 'dmap.supportsindex', 'UByteValue'),
    ('mslr', 'dmap.loginrequired', 'UByteValue'),
    ('msma', None, 'ULongValue'),
    ('msml', None, 'ContainerValue'),
    ('mspi', 'dmap.supportspersistentids', 'UByteValue'),
    ('msqy', 'dmap.supportsquery', 'UByteValue'),
    ('msrs', 'dmap.supportsresolve', 'UByteValue'),
    ('msrv', 'dmap.serverinforesponse', 'ContainerValue'),
    ('mstc', 'dmap.utctime', 'DatetimeValue'),
    ('mstm', 'dmap.timeoutinterval', 'UIntValue'),
    ('msto', 'dmap.utcoffset', 'IntValue'),
    ('msts', 'dmap.statusstring', 'StringValue'),
    ('mstt', 'dmap.status', 'UIntValue'),
    ('msup', 'dmap.supportsupdate', 'UByteValue'),
    ('mtco', 'dmap.specifiedtotalcount', 'UIntValue'),
    ('mudl', 'dmap.deletedidlisting', 'ContainerValue'),
    ('mupd', 'dmap.updateresponse', 'ContainerValue'),
    ('musr', 'dmap.serverrevision', 'UIntValue'),
    ('muty', 'dmap.updatetype', 'UByteValue'),
)

TAGS = dict([(v[0], (v[1], v[2])) for v in _TAG_DATA])
PROPERTIES = dict([(v[1], (v[0], v[2])) for v in _TAG_DATA if v[1]])

__all__ = ['TAGS', 'PROPERTIES']
